# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4WxkTrZu0gW

------WebKitFormBoundary7MA4WxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="comecar-pelo-typescript-ou-javascript-python-deno-react-native-ou-flutter.mp3"
Content-Type: audio/mpeg

< ./comecar-pelo-typescript-ou-javascript-python-deno-react-native-ou-flutter.mp3
------WebKitFormBoundary7MA4WxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/b4859470-5346-4222-8ff5-0a7bd2f688ff/transcription
Content-Type: application/json

{
  "prompt": "Kivy, Python, TypeScript, JavaScript, Deno, React Native, Flutter"
}

###

# @name generate-ai-response
POST http://localhost:3333/ai/response
Content-Type: application/json

{
  "videoId": "b4859470-5346-4222-8ff5-0a7bd2f688ff",
  "temperature": 0.1,
  "template": "Gere um resumo sucinto da transcrição do vídeo informado a seguir: '''{transcription}'''"
}