# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4WxkTrZu0gW

------WebKitFormBoundary7MA4WxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="forest-stream.mp3"
Content-Type: audio/mpeg

< ./forest-stream.mp3
------WebKitFormBoundary7MA4WxkTrZu0gW--